version: '3.8'

services:
  flask-app:
    build:
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_USER= SA
      - DB_PASSWORD = RKID#1567
      - DB_NAME = Kreedai
      - DB_HOST = localhost,1401
    depends_on:
      - sql-server


  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1401:1433"
    environment:
      - SA_PASSWORD=RKID#1567
      - ACCEPT_EULA=Y
    volumes:
      - sqlserverdata:/var/mssql

volumes:
  sqlserverdata:
